### ISSUE TITLE
product.model.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [dvoryak/shop#1]
Используйте для конструктора короткий синтаксис с модификатором доступа для параметров. Не нужно будет создавать свойства и их инициализировать.

Аналогично и при внедрении сервисов, например, тут product-list.component.ts

**Comment by dvoryak** [comment]
closed by commit #163cf59

**Comment by VZhyrytskiy** [comment]
Тело конструктора тоже можно прибрать и не делаь инициализацию
this.id = id;
        this.name = name;
        this.description = description;
        this.price = price;
        this.category = category;
        this.img = img;
        this.isAvailable = isAvailable;
