### ISSUE TITLE
product.model.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [dvoryak/shop#4]
constructor(public id: number,
                public name: string,
                public description: string,
                public price: number,
                public category: Category,
                public img: string,
                public isAvailable: boolean) {
        // this.id = id;
        // this.name = name;
        // this.description = description;
        // this.price = price;
        // this.category = category;
        // this.img = img;
        // this.isAvailable = isAvailable;
    }
Тело тоже можно убрать.

**Comment by dvoryak** [comment]
Done by @e21e7d8c65daa43908b2523816b1d5ffcc2068eb
